### ISSUE TITLE
how to return all users by specific role

### ISSUE THREAD

**Issue by nermamax** [santigarcor/laratrust#110]
I need to be able to return all users in efficient way that belong to a specific roles? How would I do this?
I tried adding this method to Role model

    public function users()
    {
        return $this->belongsToMany(User::class, 'role_user');
    }

but get:

Method users does not exist.

when doing something like this:

        $role = Role::whereName('admin')->get();
        
        dd($role->users());

**Comment by santigarcor** [comment]
It's not in the docs but search in the LaratrustUserTrait for a scope named whereRole or something similar to that.

**Comment by nermamax** [comment]
I must say this is the best package for user, roles and permissions in Laravel, thank you very much for building it and open sourcing it :)

**Comment by KKSzymanowski** [comment]
The error you got, `Method users does not exist` was because you used `->get()` and therefore tried to call this function on a Collection instance. If you want to call a function on a Role model use `->first()` instead of `->get()` but be careful because you can receive `null ` when the model is not found.
