### ISSUE TITLE
blade directive change in Laravel 5.3 (still beta!)

### ISSUE THREAD

**Issue by xenDE** [santigarcor/laratrust#12]
I use the laravel 5.3-dev at the moment for a new project.
So this info is only for testers - no fix needed for a beta release of laravel!

blade directives does not longer give the "(" and ")" as $expression:

so it becomes:

`<?php if (app('laratrust')->hasRole"root") : ?>`

LaratrustServiceProvider.php:83

```
        // Call to Laratrust::hasRole
        $bladeCompiler->directive('role', function ($expression) {
            return "<?php if (app('laratrust')->hasRole{$expression}) : ?>";
        });
```

fix:

1: use always double "((" and "))" like "@role(("root"))" (this fixes problems in other not laravel 5.3 ready libs too)

2: add the "(" and ")" in LaratrustServiceProvider.php (it's working in laravel 5.2 to, becomes double "(" and ")" but makes no problems)

i use "@role(("root"))" in blade templates for now, because i think more libs will have this problems.

**Comment by jacurtis** [comment]
This is good to know. I was having this problem yesterday and didn't understand why. I am also using 5.3-dev

**Comment by santigarcor** [comment]
Thank you for writing, i'll start working on a fix. So there'll no problem with 5.3 and 5.2

**Comment by santigarcor** [comment]
5b2eb93 Should fix it

**Comment by kennonb** [comment]
Thanks for this fix. :)

I'm seeing something weird locally for me, and I'm not sure if it's a system thing, or a change in Laravel, but the version # that is being returned for 5.3.x is `5.3.0-Dev` instead of `5.3.0-dev` which causes the `version_compare` to fail.

I can submit a PR to maybe use `strtolower` or something on the version check? Unless you have another idea there.

Or do you think it's some weird config on my local system possibly?

**Comment by santigarcor** [comment]
Actually the problem is with laravel, because if you see the version on line 28 of the `Illuminate/Foundation/Application.php` it says `5.3.0-Dev`

**Comment by kennonb** [comment]
Thanks. Yea, I dug that up after I posted this. Should've updated my post.

**Comment by santigarcor** [comment]
So i think the `strtolower` should do the job.
