### ISSUE TITLE
Upgrade migration affected by view cache

### ISSUE THREAD

**Issue by CodeGain** [santigarcor/laratrust#136]
Hi,

I stumbled upon a (I guess) rare issue when generating the upgrade migrations.
In my case I was using the latest 3.0 version and wanted to upgrade to the latest 3.2 version.

I followed the instructions here: http://laratrust.readthedocs.io/en/3.1/upgrade.html
The "php artisan laratrust:upgrade" command generated the first migration which creates the new "permission_user" table.
After upgrading to 3.1, I followed the instructions at http://laratrust.readthedocs.io/en/3.2/upgrade.html in order to upgrade to version 3.2.
The "php artisan laratrust:upgrade" command should have created the second migration which modifies the "role_user" and "permission_user" table, but it created the first migration again.

After investigating, I found out that the migration generator is affected by the view cache of laravel and "php artisan cache:clear && php artisan view:clear" fixed that issue for me.
I guess this should be noted in the installation/upgrade guide.

**Comment by KKSzymanowski** [comment]
The migration is generated from a Blade file which has the same name in 3.1 and 3.2. Maybe Laravel thought it didn't need recompiling and used the old version. It's weird because the date on the Blade file should be newer for 3.2 then for 3.1 which is supposed to force the recompilation process.

@santigarcor How about adding
```php
$this->call('view:clear');
```
before [this](https://github.com/santigarcor/laratrust/blob/3.2/src/commands/UpgradeCommand.php#L99) line?

@CodeGain what is your environment(OS, Laravel version, PHP version)? I'd like to reproduce this to see if it isn't a problem with the framework.

**Comment by CodeGain** [comment]
@KKSzymanowski 

Vagrant machine: Ubuntu 14.04, Laravel 5.3.31, PHP 7.0.13

**Comment by santigarcor** [comment]
@KKSzymanowski were you able to reproduce the error?

If that line solves the issue, i'll add it.

**Comment by KKSzymanowski** [comment]
I haven't tried this yet. My VM with Ubuntu is currently being set up. I'll let you know if I figure something out.
