### ISSUE TITLE
Verify the role always returns true

### ISSUE THREAD

**Issue by AnvarGear** [santigarcor/laratrust#153]
Hello,

I'm implementing the permissions and I get to a drawback and is that if I make a query with the method "hasRole" with parameters in array always returns false.

The code used is:

`        $user = User::find($requisicionA->user);
        dd($user->hasRole(['jefedearea', 'god', 'superadmin']));`

Try changing the role of user '1' to a different one than the three described in the code and still returns me as true.

These are the characteristics of my installation:

Laravel 5.4.*
PHP 7.0.*
Laratrust 3.2.*

Thanks in advance.

**Comment by santigarcor** [comment]
Did you changed the role directly in the DB or through code? Because if you did it via DB you have to clear your application cache.

And also if your user has any on those three roles, it's going to return true, because its an **OR** check. If you want to check for all of them pass a second argument as true:

`$user->hasRole(['jefedearea', 'god', 'superadmin'], true);`

**Comment by AnvarGear** [comment]
Hello,

I really made the changes from the DB, I'll try again.

Thanks for the prompt response.
