### ISSUE TITLE
Question: multiple owners

### ISSUE THREAD

**Issue by michaelcurry** [santigarcor/laratrust#174]
Looking at `\Laratrust\Contracts\Ownable` it looks like only one user can own an object.  Is there a way to allow multiple users to own an object? 

On a side note, this package looks amazing and am very happy someone took the time to create something so Eloquent ;)

**Comment by santigarcor** [comment]
@michaelcurry i had that same problem. So if you want you can use the master branch. There i pass the `$owner` to the `ownerKey` method.

With that change you can resolve the ownership depending on the type of the `$owner` object.

**Comment by michaelcurry** [comment]
@santigarcor: when do you think master will be put into a tagged release?  I am a little uneasy using master because I am dealing with production code.  If for some reason files were to change that breaks the current version of master, my life would be very sad :(

**Comment by santigarcor** [comment]
The thing is that i can't put that code into a release tag because it would be a breaking change, so i will change more things to make the next release worth it.

For now why don't you use:

`"santigarcor/laratrust": "dev-master#bfc5d453aee8bbd1344631bb5cf7304c1ba02716"`

so if i make changes you won't have any problem.

**Comment by michaelcurry** [comment]
Will do, and thanks for the quick replies!

I am currently evaluating and may have more questions (I will create another issue other questions)
