### ISSUE TITLE
Teams documentation/implementation

### ISSUE THREAD

**Issue by nrcsantos** [santigarcor/laratrust#182]
While i'm giving my first steps with Laratrust i tried to understand the best method i can use to apply it to my needs and i ended up seeing the 'Teams' as a must on my solution.

I need Roles, Permissions assigned to the Roles and Roles linked to Teams (or Groups).

Idea is simple and giving this example, a Group(team) called "Laratrust Developers" will have members with Roles "Admin", "Contributor" and "Member" and on each of this Roles i will have Permissions such as "Can Post", "Can Edit", "Can Manage Users", etc...

From what i've seen people limit them to Roles & Permissions and it's very well documented, but on the Teams part there's nearly nothing on this subject... 

I need to get some abilities like:

$LaratrustDevelopers = Teams::where('name', 'Laratrust Developers')->get();

or

@if($userHasTeam ...

Any documentation or confirmation if it's doable or not?

**Comment by santigarcor** [comment]
Theres enough documentation about the teams feature and how it works, you can check it [here](http://laratrust.readthedocs.io/en/4.0/configuration/teams.html) and [here](http://laratrust.readthedocs.io/en/4.0/usage/concepts.html#teams).

The way you implement if your user has a team or not, is not part of the package, because we are only interested in the authorization part (check if a user has a role/permission, and in your case if the user has the role/permission inside a team).

**Comment by nrcsantos** [comment]
Thank you for your feedback... i was trying to extend the Teams functionalities but i see your point.
