### ISSUE TITLE
[Question] Migration from Entrust

### ISSUE THREAD

**Issue by gsaqui** [santigarcor/laratrust#192]
I see that we now have a `user_type` on `role_user` and `permission_user`.  I'm confused on what should I be setting that value to.

I have an admin role - would the `user_type` be set to `admin` or something else?

If there is a link to that in the documentation that I missed I'm terribly sorry.  Is there documentation for people moving from entrust?

**Comment by santigarcor** [comment]
The user type is because the relationship is now a [Many To Many Polymorphic](https://laravel.com/docs/5.5/eloquent-relationships#many-to-many-polymorphic-relations) relation so if your user is `App\User`, then that fully qualified class name should be the value for the `user_type` column as the Laravel documentation explains.

**Comment by gsaqui** [comment]
Thank you for your help.
