### ISSUE TITLE
What about method hasRole() for Permission Model?

### ISSUE THREAD

**Issue by njxqlus** [santigarcor/laratrust#195]
Hello!
I was confused when check LaratrustPermissionTrait and don't find hasRole() method.
I follow the next logical chain:
User model have:
- roles() method
- hasRole
- permissions() method
- hasPermission

Role model have:
- permissions() method
- hasPermission

Permission model have:
- roles() method

As u can see before if model have one of belongsToMany method it also have the "has" alternative.

I use these methods in views but I new in Laratrust and maybe u can offer me another decision?
```php
//user edit view
$checked = $user->hasPermission($permission->name) ? ' checked': '';
```
```php
//user edit view
$checked = $user->hasRole($role->name) ? ' checked': '';
```
```php
//role edit view
$checked = $role->hasPermission($permission->name) ? ' checked': '';
```
And I want next:
```php
//permission edit view
$checked = $permission->hasRole($role->name) ? ' checked': '';
```

**Comment by KKSzymanowski** [comment]
It doesn't really make sense to me to add a `hasRole` method to the permission object.

**What would it mean for a permission to have a role?**

A user can have a permission(or a role) because someone granted it to them. It authorizes them to perform certain actions.
A role can have a permission because it can be seen as an aggregate for permissions. Granting a certain role can mean a user will be automatically granted some permissions which this role has.

A permission having a role doesn't fit in this structure.

Can you explain what exactly do you want to check by calling:
```php
$permission->hasRole($role->name)
```
Can you provide a real-life example of a use case for this functionality?

**Comment by njxqlus** [comment]
@KKSzymanowski thank you for the answer.
I provided real-life example in my first message. I want to check something like this: Is this permission belongs to the role?

The real thing why I so confused: Permission model have `$permission->roles`. It's do the same - return roles that belongs to the permission.
```php
public function roles()
    {
        return $this->belongsToMany(
            Config::get('laratrust.models.role'),
            Config::get('laratrust.tables.permission_role'),
            Config::get('laratrust.foreign_keys.permission'),
            Config::get('laratrust.foreign_keys.role')
        );
    }
```

**Comment by KKSzymanowski** [comment]
> I want to check something like this: Is this permission belongs to the role?

Ok, I think I get it now.
Yes, you might consider it an inconsistency, but I'd never name the method in question `Permission::hasRole()`, because permission cannot **have** a role, it can only **belong to** one(just like role cannot **have** a user, a role can **belong to** a user).
`Permission::belongsToRole()` makes more sense but I have never come across a situation where I needed to check that, that's why I'm having trouble understanding what do you want to achieve. 

Also, I don't quite get your example. What precisely are you trying to do?
Do you want to edit a permission and choose which roles it will belong to?
![image](https://user-images.githubusercontent.com/13980973/30485294-37556c42-9a2d-11e7-8831-917030cdffad.png)
If so, if feels to me like you're doing it the wrong way. You should assign permissions to roles, not the other way around.
