### ISSUE TITLE
How to override user permission over role permission?

### ISSUE THREAD

**Issue by bigbharatjain** [santigarcor/laratrust#208]
Hello @santigarcor 
Thanks for the great package and +1 for continuous improvement.
I want to ask, if any role is assigned to a user, and I want to change some permissions for some specific user then how can I check, if user has that permission or not?
I have attached specific permissions for that user in permission_role table, but it still shows all permissions for that user.
Can you let me know how to override specific user permission over role permission?
Thanks

**Comment by santigarcor** [comment]
- To check if a user has a permission use the ``can``, ``isAbleTo`` or ``hasPermission`` methods as you can see in the docs.
- If you attached the permission directly in the database you have to clear your app cache or disable the cache usage(only in Laratrust 5.0), otherwise you are not going to see the changes you made.
- You can't override a permission. The only way is to remove the permission from the role or create a new role without the permission you want.

**Comment by bigbharatjain** [comment]
Ok, Got it.
If I want to give specific permissions then I have to remove that user from the role and attach the required permission.
Thanks
