### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::sync()

### ISSUE THREAD

**Issue by uniquechukwuma** [santigarcor/laratrust#299]
Call to undefined method Illuminate\Database\Query\Builder::sync()

Please why cant i sync successfully even attachRoles and Permissions are failing

BadMethodCallException
Call to undefined method Illuminate\Database\Query\Builder::attachRoles()

it seems not to recognize the methods
please help.

my Model

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    protected $fillable = [
        'name', 'display_name', 'description',
    ];

    public function users(){

        return $this->hasMany('App\User');
    }

    public function department(){
        return $this->hasMany('App\Department');
    }

    
    public function permission(){
        return $this->hasMany('App\Permission');
    }

}

Controller 

public function destroy($id)
    {
        // $role = Role::find($id);
      
        // // $role->users()->detachRoles([]);
        // $role->users()->sync([]);
        // $role->permissions()->sync([]);
        // dd($role->id);
        // $role->forceDelete();

        // //$role->delete();
        // return redirect()->back();

        //
        try {
            $role = Role::findOrFail($id);

          
            // Force Delete
            $role->users()->sync([]); // Delete relationship data
            $role->permissions()->sync([]); // Delete relationship data

            $role->forceDelete(); // Now force delete will work regardless of whether the pivot table has cascading delete

            return redirect()->route('roles.index')->with('success', "The Role $role->name has successfully been archived.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    } and i got the above error

**Comment by KKSzymanowski** [comment]
The `sync` method is available only in `belongsToMany` and `morphToMany` relationships.
You have a `hasMany` relationship, that's why the error is thrown.

***

Side notes:
1. You don't have to define the `permissions` relationship on your role model. It is already defined in the `LaratrustRoleTrait` used in `LaratrustRole` model.

2. If you have a `catch` clause for `ModelNotFoundException` you don't have to check if the exception is an instance of `ModelNotFoundException`.

3. I don't think the `try-catch` block is necessary. I think if the model is not found using `findOrFail` Laravel automatically renders the `errors.404` view. If it doesn't however I would replace the `try-catch` block with
    ```php
    $role = Role::find($id);
    
    if (!$role) {
        return view('errors.404');
    }
    
    // Further code if role was found
    ```
    It's cleaner and should be a little bit faster.

4. Please wrap code in tripple backticks on Github. It's much easier to read. 
    For example:
    > \```php
    > $foo = Class::CONSTANT;
    > \```

    renders as 
    ```php
    $foo = Class::CONSTANT;
    ```
    Further reading: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by uniquechukwuma** [comment]
Thank you very much it works but i still have issues when i attached roles during permission creation it gives me errors. BadMethodCallException
Call to undefined method Illuminate\Database\Query\Builder::attachRoles()  please do i attach the code?

**Comment by KKSzymanowski** [comment]
Yes, please attach the code.

**Comment by uniquechukwuma** [comment]
<h1>This is the controller</h1>
php

public function store(Request $request)
    {
       
        $this->validate(request(), [
            'name' => 'required',
            'display_name' => 'required',
            'description'=> 'required',
            'department_id'=>'required'

        ]);

        // dd("ddsds");
        $permission = new Permission;

        $permission->department_id = $request->input('department_id');
        $permission->name = $request->input('name');
        $permission->display_name = $request->input('display_name');
        $permission->description = $request->input('description');
        
        $role = [];
        $role = $request->input('role_id');
      
        if(!$role){
            
            $permission->save();
        }else{
            $permission->save();
            $permission->attachRoles($role); 
        }
        
       
         return redirect(route('permissions.index'))->with('success', 'IT WORKS!');

    }


php


<h1>The Model</h1> 

php

<?php

namespace App;

use Laratrust\Models\LaratrustPermission;
class Permission extends LaratrustPermission
{
    public function users(){

        return $this->belongsToMany('App\User');
    }

    public function role(){
        return $this->belongsToMany('App\Role');
    }
 

    
}


php

**Comment by uniquechukwuma** [comment]
Thanks in anticipation please. This is my first project on  laravel/Laratrust sorry if the code looks clumsy

**Comment by KKSzymanowski** [comment]
First of all, I have never dynamically created permissions in my apps. It just doesn't make sense to me. Permissions are often hardcoded in the app, something like `$user->can('generateFinancialReport')` so I don't imagine any use for creating them dynamically.
However if this makes sense for your app, that's ok.

You have this error because there is no such method `attachRoles` for permissions. It also makes little sense to me. I'd rather attach a permission a role than the other way around and I'd recommend this approach.
For example:
```php
$permission->save();

$role = Role::find($request->input('role_id'));

if ($role) {
    $role->attachPermission($permission);
}
```

**Comment by uniquechukwuma** [comment]
There are methods like this in laratrust document

$user->attachRole($admin); // parameter can be a Role object, array, id or the role string name
// equivalent to $user->roles()->attach([$admin->id]);

$user->attachRoles([$admin, $owner]); // parameter can be a Role object, array, id or the role string name
// equivalent to $user->roles()->attach([$admin->id, $owner->id]);

i dont know why its not working for me

**Comment by uniquechukwuma** [comment]
Thank you. A colleague just told me i cant attach permission to roles rather i attach roles to permission
