### ISSUE TITLE
Change name column in team middleware

### ISSUE THREAD

**Issue by eaponiente** [santigarcor/laratrust#337]
Is it possible that in the middleware it would instead look in the teams by a different column rather than name?

```
'middleware' => ['permission:edit-post|edit-user,my-awesome-team,require_all']
```

my-awesome-team is a name column, right now my structure looks like this...

id, name, code etc..
1 | Sports Complex | SC

what I want is to use the SC code in the middleware instead of name

Is it possible that a role can be used by multiple teams? below is not working
```
['ability:admin,some-permission,Team 1|Team 2,require_all']
```

**Comment by santigarcor** [comment]
1. The team has two columns, `name` and `display_name`, the name should be used as the code, and the display name as the long name you have there.
2. That middleware only works for one team that's why it's not working. Then you will have to implement a custom validation there in order to support multiple teams inside that middleware.
