### ISSUE TITLE
 Upgrade from 5.1 to 5.2

### ISSUE THREAD

**Issue by mr-masoud-momeni** [santigarcor/laratrust#373]
- Laravel Version: #.#.# 
- Laratrust Version: #.#.# 

### Description:
I did not understand step 4 from update. Please explain

**Comment by KKSzymanowski** [comment]
If you mean this step:
```
Update your config/laratrust.php in the cache ttl from 60 to 3600 or the value you had but now put it in seconds.
```
Laravel previously accepted a number of minutes when you wanted to cache something for example using `Cache::remember()` method. 
Now however Laravel expects the number of seconds not minutes, so you need to update the Laratrust cache TTL (time to live).
As stated in the documentation you will find id in `config/laratrust.php`.

**Comment by KKSzymanowski** [comment]
Looks like you have the configuration file from Laratrust 5.0.
You should look at the newest file version [here](https://github.com/santigarcor/laratrust/blob/5.2/config/laratrust.php) and correct the differences.

If you previously used Laratrust <= 5.0 and configured the cache TTL you might have the `ttl` key in the `config/cache.php`. In that case you can safely delete this entry because it is no longer used by Laratrust.

If you haven't ever changed the Laratrust config you can try deleting the file altogether and creating it again using `php artisan vendor:publish`.
