### ISSUE TITLE
Laravel 8 jetstram Teams

### ISSUE THREAD

**Issue by GeoSot** [santigarcor/laratrust#448]
Hello @santigarcor 

Along with the laravel 8,  jetstream package is introduced as default, to handle authentication functionality.

As I have seen, it brings teams functionality, which bring new variables on the table.

I would like to ask if you are aware of it and if you have thought any way to combine or separate the two teams (yours and jetstream) Models and functionality

**Comment by santigarcor** [comment]
@GeoSot I saw Taylor's talk about it, and to be honest I haven't thought about combining them. But it would be the way to go.

I believe some hacky solution(for now) would be to change all the Laratrust's configurations to use jetstream's teams table and model, but leaving the intermediate tables as they are.

**Comment by jigzstar** [comment]
> @GeoSot I saw Taylor's talk about it, and to be honest I haven't thought about combining them. But it would be the way to go.
> 
> I believe some hacky solution(for now) would be to change all the Laratrust's configurations to use jetstream's teams table and model, but leaving the intermediate tables as they are.

Tried to this but got this error here:
```php
Trait method Laratrust\Traits\LaratrustUserTrait::allTeams has not been applied as App\Models\User::allTeams, because of collision with Laravel\Jetstream\HasTeams::allTeams
```

so did this:
```php
    use LaratrustUserTrait {
        LaratrustUserTrait::allTeams insteadof HasTeams;
    }
```

Seems to be working so far.

**Comment by patake** [comment]
Hi @santigarcor , I believe that I'm having some other error related to teams of jetstream.

While learning about laratrust and exactly on this point of the docs: https://laratrust.santigarcor.me/docs/6.x/usage/roles-and-permissions.html#assignment-2 , I'm receiving this error while testing it:

![image](https://user-images.githubusercontent.com/22771185/109876706-d6ecc080-7c50-11eb-95eb-002f18a658ca.png)

Well, the error is quite logic, but I'm afraid that the laratrust install didnt make the right modification on migrations, because this field doesnt exists on migration file...

If I create this field on role_user table, maybe the error go away but it's the right way to fix it?

Thanks

**Comment by tony-riela** [comment]
> > @GeoSot I saw Taylor's talk about it, and to be honest I haven't thought about combining them. But it would be the way to go.
> > I believe some hacky solution(for now) would be to change all the Laratrust's configurations to use jetstream's teams table and model, but leaving the intermediate tables as they are.
> 
> Tried to this but got this error here:
> 
> ```
> Trait method Laratrust\Traits\LaratrustUserTrait::allTeams has not been applied as App\Models\User::allTeams, because of collision with Laravel\Jetstream\HasTeams::allTeams
> ```
> 
> so did this:
> 
> ```
>     use LaratrustUserTrait {
>         LaratrustUserTrait::allTeams insteadof HasTeams;
>     }
> ```
> 
> Seems to be working so far.

Do you have an example of how you added laratrust support inline with jetstream teams? I was going to use spatie permissions but actually need laratrusts individual based  user team permissions and hit a wall with the jetstreams clash.
