### ISSUE TITLE
Assign permissions on Team

### ISSUE THREAD

**Issue by GeoSot** [santigarcor/laratrust#456]
Hello, 
###  **It's not a bug**

It have past some time from the last time I used the package, and I am trying to remember again it's functionality.
So I would like a friendly advise/answer

I have a project that support teams, and roles inside teams. Till here we are ok

Some questions that messed up my mind:

1. Is there any way, where I can attach permissions to a Team and after this, a user  inherit these permissions?

2. The ability 'owns'  is checking the owner (USER). Can be changed to check ownership though team or can I use a work around?

3. can I use any build-in method to get **all** user teams ? Including these that has from `permission_user` table for now I think there is only a roleTeams relation. Am I wrong?

A relation like this could do the job?
```php
    /**
     * Many-to-Many relations with Team associated through the roles.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function permissionTeams()
    {
        if (!Config::get('laratrust.teams.enabled')) {
            return null;
        }

        return $this->morphToMany(
            Config::get('laratrust.models.team'),
            'user',
            Config::get('laratrust.tables.permission_user'),
            Config::get('laratrust.foreign_keys.user'),
            Config::get('laratrust.foreign_keys.team')
        )
            ->withPivot(Config::get('laratrust.foreign_keys.permission'));
    }
```

Thank you in advance for your answers

**Comment by santigarcor** [comment]
1. There isn't a built in way to do that right now.
2. If you implement the Ownable interface i think you can do that custom logic. I even extracted that ownable functionality into its own [package](https://github.com/santigarcor/laravel-ownable), so maybe you can use it there. I'm planing on removing it from Laratrust and to refer to that package.
3. There isn't a built in way to get those teams, because that relationship is not necessarily the same as the one that associates the roles.

And I think you're right about the `permissionTeams` relationship. It is not defined in the trait

**Comment by GeoSot** [comment]
2.Thank you for you advice. and it's a good idea the decoupling you are thinking about
3. I made a [MR](#460 )  to cover this. 

Sorry for the too many MRs. I am planning a work project, and I am always the lucky man who fells into the exception to the rule
