### ISSUE TITLE
Testing the 4.0.0-rc.1 version

### ISSUE THREAD

**Issue by santigarcor** [santigarcor/laratrust#49]
Hi everybody,

i would like to ask everyone if you can test the new version, in order to check that the new groups integration is working fine and has all the needed interfaces and features to make it work easily.

Thanks!

**Comment by andcl85** [comment]
Tested group integration so far and working just fine. Will test it extensively in the next few days.

**Comment by santigarcor** [comment]
Nice, thank you.

Tell me if something is wrong in order to fix any problem.

**Comment by andcl85** [comment]
I have realised that there is a relatively big inconsistence in the package: 
When something different to the default `group_id` is configured in `config/laratrust.php` for `group_foreign_key` parameter, package does not work at all because checks are steadily done in Trait classes against the **HARDCODED** `group_id` property (e.g., in line 166 of laratrust/src/Laratrust/Traits/LaratrustUserTrait.php, amongst many others).
