### ISSUE TITLE
How can I define multiple user relationships with other models using laratrust?

### ISSUE THREAD

**Issue by AbdelazizTina-dev** [santigarcor/laratrust#499]
Hello everyone,
So I'm trying to create different relationships between my user model which have two types (teacher and student) and another model which is subject, basically teachers have 1-N relation with subjects and students have N-N, any guidance is much appreciated, thanks.

**Comment by KKSzymanowski** [comment]
> I'm trying to create different relationships

If you need different relationships then I don't see a problem.
```php
class User extends Model {
    public function subjectsTaught() {
        return $this->hasMany(Subject::class, 'teacher_id');
    }

    public function subjectsLearned() {
        return $this->belongsToMany(Subject::class);
    }
}
```

In any case, I don't think this has anything to do with Laratrust.

**Comment by GregPeden** [comment]
A pattern I use in my application is to attach a slightly customized "team" model to many things for which I need to describe the relationship various users have with that thing. So in my case all projects have a team, every company office has a team, and even users themselves have a team so that I can assign special permissions such as letting nominated people enter timeslip records for some special case employees/users.

**Comment by filippotoso** [comment]
If you need to handle different types of user models, you could take a look to [this approch suggested by Caleb Porzio](https://tighten.com/insights/extending-models-in-eloquent/).
