### ISSUE TITLE
Suggestion: Add means for user to assume permissions of another user

### ISSUE THREAD

**Issue by GregPeden** [santigarcor/laratrust#503]
As a suggestion, add a method for a user to assume the permissions of another user. Two modes:

Additive permissions (base user retains existing permissions + assumes permissions of other)
An example application for this is a person covering for another while on vacation.

Replace permissions (base user has permissions of other only, not their own)
Application for this is easy debugging in a dev environment by quickly toggling between the permissions on other faux user accounts set up to simulate typical expected users. Also, debugging live production build in response to feedback from a user.

There would need to be a way to bypass/disabling this when checking permissions in desired contexts, because this would be important to do while actually performing the permission swapping itself.

Note I am not proposing this package provide a UI to do this, just the PHP interface to affect it, and then it's up to the developer to provide UI solutions or whatever to make use of the feature.

**Comment by filippotoso** [comment]
I don't think this should be baked into the package because the way permissions (and roles) are used depends too much on the application side.

For instance, in small projects I usually relay on roles instead of permissions and use the user id to protected access to 
"owned" resources. In this cases, I use impersonation to handle use cases like covering for another user while on vacation.

The proposed solution will not work because, in my case, a user will not be able to interact with models "owned" by other users even if he has assumed their permissions.

This maybe implemented in an external package with documentation about how to handle models ownership.
