### ISSUE TITLE
User wise redirect after Login

### ISSUE THREAD

**Issue by aminkhannsu** [santigarcor/laratrust#54]
Hello, 
I am new in Laravel. I am trying laratrust for role wise authentication. Can any one tell me, how to redirect user according to their role after login.
I.E:
Admin User
Redirect to : /admin

Employee User
Redirect to: /employee

**Comment by KKSzymanowski** [comment]
The simplest solution would be to say:
```php
public function someControllerMethod()
{
    // Authentication logic

    $user = auth()->user();

    if($user->hasRole('admin')) {
        return redirect('admin');
    } elseif($user->hasRole('employee')) {
        return redirect('employee');
    } else {
        return redirect('somewhereElse');
    }
}
```

You can also consider [naming your routes](https://laravel.com/docs/5.3/routing#named-routes). That way, when the URL changes, you don't need to update it in every place.
If your route is named you can redirect in a following way:
```php
return redirect()->route('nameOfTheRoute');
```

If you're new to Laravel, be sure to **return** the redirect response. Otherwise you'll see the blank page.

**Comment by aminkhannsu** [comment]
Perfect. Thank you @KKSzymanowski. 

Another query:
I am using laravel 5.3 . I tried to use `Laratrust::routeNeedsRole('admin/advanced*', 'owner', Redirect::to('/home'));` this in my route file web.php . But it shows error
 `BadMethodCallException in Macroable.php line 74:
Method filter does not exist.`

any suggestion??
