### ISSUE TITLE
Global administrator, allowing all permissions

### ISSUE THREAD

**Issue by Naamloos** [santigarcor/laratrust#637]
Hi! 

I am currently working on a project that uses Laratrust, and I was wondering if it was possible to define a role that automatically gets all allowed permissions?

Currently our system solves this by having a copy of every permission prefixed with `superadmin-`. I'd like to change that to a simple boolean on a role that when set to `true` will return success on any permission check. 

Is something like this possible natively with Laratrust? I had considered overriding some methods on the `LaratrustUserTrait` trait, but quickly figured out that that might not be the best way?

Thank you in advance!

(This project uses laratrust 6.1.0)

**Comment by filippotoso** [comment]
Intercept the created event in the Permission model and attach the created permission to the superadmin role.

**Comment by Naamloos** [comment]
I don't think this quite suffices as a proper solution to this problem. It sounds more like a workaround than a proper solution. 

(Thank you for your response anyway, I appreciate the effort)

**Comment by filippotoso** [comment]
Without modifing Laratrust behaviour there are only 2 ways to do what you need.

The first one is to keep the SuperAdmin role permissions in sync with all the available permissions (see above for the implementation)

The second one is to add a check for the SuperAdmin role everytime you check for permissions (ie. if the user has this permission OR is has the SuperAdmin role).

Otherwise, you have to change the Laratrust behaviour to check for the single permission OR check for the SuperAdmin role.

From my point of view, the first solution is the easies and cleanest of all of them.

**Comment by santigarcor** [comment]
How I've made it in the past is by defining one permission that only super admins have and in side the policies i check if the user has that permission or the actually required permission. or by simply adding all the permissions to the admin.

**Comment by Naamloos** [comment]
even though it's not exactly the solution I was looking for, it _is_ a better solution than what was proposed before, in my honest opinion. Thank you both for your help. I'll propose this change internally.
