### ISSUE TITLE
User owns + @permission in blade?

### ISSUE THREAD

**Issue by ahjorth** [santigarcor/laratrust#86]
Say I allow my users to edit their own posts, and any user who has the permission `edit-post`

`@permission('edit-posts')`

works fine, but will I then have to do this to check for owner?

`@if(\Laratrust::can('edit-posts') || Auth::user()->owns($post))`

That looks ugly. Is there some easier way of doing this in blade?

**Comment by santigarcor** [comment]
Currently there's no easier way to this, but i can add a new directive that makes it easier to the user. Have you thought about some name for the directive?

**Comment by ahjorth** [comment]
I was thinking about it, but everything I thought of sounded weird.

Currently I can't find any blade directives that use camelcase. They are all limited to single word directives, which makes things like this more difficult.

`@permissionOrOwns('edit-posts', $post)`

This just looks... strange.

I guess it could be possible to add the resource as the second `@permission` parameter
`@permission('edit-posts', $post)` sort of like how laravel deals with authorization.

However, this presents the issue of column names. Each model can have their own foreign key for user, like `user_id`, `owner_id` and `author` etc.

So it could default to look for `user_id` but an optional **third** parameter can be put in to specify key
`@permission('edit-posts', $post, 'author_id')`

Then again, this all looks very clunky, and I'm sure someone can figure out something better.

**Comment by ebarault** [comment]
hi, 
would that be possible that we treat the **`"owner"`** as a smart role instead of allowing people to use this name as a standard role which you statically attach to a user ?

As such the **`"owner"`** role would use the `$user->owns()` method under the hook to dynamically resolve whether a given user effectively has the **`"owner"`** role on the targeted model instance. 

- Of course we'd need to define a syntax to pass the reference to the targeted model instance
- Permissions would also need to be attachable to this smart role.

The current syntax for roles could then break into a more advanced one when needed
```blade
$user->hasRole([[name=>'owner', target=>$post], 'admin']);
```
While we'd still need to figure how to pass the target reference in blade directives and in middleware registrations, as well as in syntax shortcut sugars.

Thoughts?

**Comment by santigarcor** [comment]
@ebarault I think that solution makes everything more difficult. An easier approach would be to create a method and a blade directive that below uses both methods.

As @ahjorth  said a method or a directive like `canAndOwns` and the params for the method:

`canAndOwns([$permissions, $requiredAll], [$thingToCheckOwnership, $foreignKey])`

**Comment by ebarault** [comment]
this syntax does not look intuitive IMO
I guess something of the like is then more preferable as fully explicit, 100% flexible in composition and less error prone

`@if(\Laratrust::can('edit-posts') || Laravel::owns($post))`

(then we'd also need `abilityAndOwn`, `roleAndOwn`, etc.)

_**Just a note**: the concept of smart/dynamic roles is taken from other api frameworks i'm used to work with and is really powerful. I find difficult to grasp a concept of static owner role as depicted in your documentation examples where you need to attach it as a whole to a user : **"what the user is actually owner of actually?"**.
Yet i totally get your POV considering the current implementation and your will not to go for it_

**Comment by ahjorth** [comment]
At least there is a history of camelcase directives in blade so it wouldn't be too outrageous.

`@hasSection` (can't find it in 5.4 docs, so might be deprecated, but then again it might still be there)

Seems like `@canAndOwns` or `permissionAndOwns` might be the best way so far.

Maybe even add an `Ownable` trait or require the property `protected $ownerKey = 'author_id'` on each model, making it possible to simply add any post or class reference to the `@permission` directive

`@permission('create', Post::class)`
`@permission('update', $post)`

This is how Laravel does it with the `@can` directive and Authorization

**Comment by ebarault** [comment]
+1 for the Ownable trait to use in models

**Comment by santigarcor** [comment]
The first one doesn't make any sense because you can check it with one permission. The other one is not that bad, but i think it is better with an interface than a trait.

So the directive would end like this:

`@permission('update-posts', $post)`
or
`@permission(['update-posts', 'delete-posts'], $post)`
or
`@permission(['update-posts', 'delete-posts'], true, $post)`

We can't forget that the `requireAll` parameter exists. Another thing to have in mind is that when this code get merged with the groups integration it's going to get tricky because we will have to add it the group

**Comment by ebarault** [comment]
Good point : an interface will allow people to define their own
implementation of the way the ownership is resolved, on a per model basis.

Generalization could still be achieved by extending a generic base model

Le mar. 14 févr. 2017 à 07:48, Santiago García <notifications@github.com> a
écrit :

**Comment by santigarcor** [comment]
Exactly, the interface can force the class to have a method that returns the foreign key to check against the user.

**Comment by santigarcor** [comment]
@ebarault I just added the owns method to the Laratrust facade

**Comment by ebarault** [comment]
@santigarcor: Thanks!

**Comment by ebarault** [comment]
i'll have to wait you port to master though :)

**Comment by santigarcor** [comment]
@ebarault  I'm working in the ownable trait and change the directives and methods then i'll port everything to the master branch.

I would have to create to new directives and two methods, because if i change the `can` and `hasRole` method, things are going to get trickier in the master branch with the groups.

**Comment by ebarault** [comment]
@santigarcor: 👍 , i didn't mean to rush you at any point. I'm currently using the feature through the Auth façade

**Comment by santigarcor** [comment]
845ad99 solves this issue
