### ISSUE TITLE
multi-tenancy

### ISSUE THREAD

**Issue by EmadAdly** [santigarcor/laratrust#96]
Greetings to you on this package. Your activity is unprecedented

I would ask about multi tenant are there any idea or a possibility to get around to working under multi tenant architecture.

Thank you,

**Comment by KKSzymanowski** [comment]
Can you expand on that, maybe provide an example?

**Comment by EmadAdly** [comment]
ok, I mean specifically multi-tenant of shared schema style. 
in other words, all tenants accounts within a single database and also the users for example shared within a single table so we separated through a custom id column for each Tenant

this architecture is use in many apps such as Slack and Trello etc.

The question here : is there a way to use this package in this architecture? also  In other words, as an example I needs to add a custom column to separate tenants inside your package scheme so that can processing the role and permission for the users in each tenant scope.

**Comment by santigarcor** [comment]
It sounds me like the groups feature.

I did the groups feature in the master branch, but after all the changes i've made to the current Laratrust release and the new one with multiple user models support, i'll rewrite it using the multi-user branch.

So i can't assure you direct compatibility if you use that master branch and i don't know when i could finish that because i won't have that much time for the next two months.

**Comment by jsdecena** [comment]
I know that this is already closed by I am doing the same architecture but separate schema. Every user on each app will have different roles/permissions. But another question arises, how to use the role package together with API since this package is checking the logged in user via session. 😄

**Comment by santigarcor** [comment]
@jsdecena Are you referring to the middleware? Because that is the only part where the user is fetched with the auth()->user(). You could simply copy the middlewares, and change the line to what you need, and use them as always.

**Comment by jsdecena** [comment]
@santigarcor Yes I am referring to the middleware. I have a related resolution in [here](https://github.com/santigarcor/laratrust/issues/138#issuecomment-314070968)

The problem is when the JWT is authenticated, we do not know who is logged in so we need a way to log in the user. `$this->auth->user()` will be `null` since there is no user being logged in so I have to login the user when it has successfully authenticated via `Auth::onceUsingId($user->id)` and the guards for the role / permission will work now.

**Comment by santigarcor** [comment]
But that problem is not Laratrust problem, because you are talking about authentication. Laratrust is interested in the logged in user roles, permissions and ability, Laratrust doesn't login the user.

Maybe i have to change the `$request->user()` to `$this->auth->user()` but from there, i think the problem is with the authentication system.

**Comment by jsdecena** [comment]
@santigarcor Yup, there is no problem with the Laratrust package. It's just the `users` should be **logged** in the application to make use of this package. More power to you sir and thank you!
